apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: mjc-ambulance-ufe-content
spec:
  microFrontend: mjc-ambulance-ufe
  # aplication context element
  element: mjc-ambulance-wl-app
  attributes:
    - name: api-base
      value: http://localhost:5000/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?mjc-ambulance-wl(/.*)?$"