apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: mjc-ambulance-ufe-content
spec:
  microFrontend: mjc-ambulance-ufe
  # aplication context element
  element: mjc-ambulance-wl-app
  attributes:
    - name: base-path
      value: /mjc-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?mjc-ambulance-wl(/.*)?$"