apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: johnzeki/ambulance-ufe
  newName: johnzeki/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main202503111404 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
